### ISSUE TITLE
Expose EuCookieLawPopup()

### ISSUE THREAD

**Issue by lordarthas** [wimagguc/jquery-eu-cookie-law-popup#1]
Even though the documentation says it's possible to enter parameters with code such as this:

    (new EuCookieLawPopup()).init({
      // ...
    });

This actually doesn't work, as  EuCookieLawPopup() is not available outside the closure where it's defined. I removed the "var" before its definition, so it's a global variable. Now it works, but there should be a more elegan solution. ;)

**Comment by wimagguc** [comment]
Thanks @lordarthas! This should be fixed in 6e761a2c7ebd3a6d05aaa197ee93394667897fd7
