### ISSUE TITLE
Allow to pass z-index as parameter to init() - or use a very high one as default

### ISSUE THREAD

**Issue by lordarthas** [wimagguc/jquery-eu-cookie-law-popup#2]
Some web site have a menu bar or other things with a very high z-index.

So, I'd say, either enter a very high z-index in the default cookie-law plugin default CSS file (such as 9999999) or allow it to be overridden with a parameter to the init() method.

**Comment by wimagguc** [comment]
This one is fixed as well, in 7a67e4ee672b2df808f97a12f08b9070a0b1b0e3.

No need to include this within the params. In the worst case, adding a simple line ".eupopup-container { z-index: XX; }" in any css file (loaded late enough) does the trick.
